# Site settings
title1: "EMNLP 16 "
title1_16: "EMNLP 16 "
title1_17: "EMNLP 17 "
title1_19: "NAACL 2019 "
title1_20: "EMNLP 2020 "
title1_21: "ACL-IJCNLP 2021"
title2: "Workshop on Structured Prediction for NLP"
title3: "5th Workshop on Structured Prediction for NLP"
email: structured-prediction-workshop-org@googlegroups.com 
#description: "EMNLP 16: Structured Prediction for Natural Language Processing"
baseurl: ""
url1_16: "http://www.emnlp2016.net"
url1_17: "http://www.emnlp2017.net"
url1_19: "https://naacl2019.org"
url1_20: "https://2020.emnlp.org"
url1_21: "https://2021.aclweb.org"
url2: "http://structuredprediction.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
